/** Fixed Feature Court cast — injected by edge functions, not generated by AI. */
export const CAST = {
  bailiff: {
    name: "Bailiff Sprint",
    color: "#a67c00",
  },
  judge: {
    name: "Judge Ship Itwell",
    color: "#6b7280",
  },
  prosecutor: {
    name: "Prosecutor Mary T. Bug",
    title: "Staff PM · Bug hunter since day one",
  },
  defense: {
    name: 'Defense Attorney Edward "Edge" Case',
    title: "Principal PM · Edge case specialist",
  },
} as const;
